# Generated by Django 4.1.7 on 2023-02-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image_url',
            new_name='image',
        ),
    ]
