# Generated by Django 4.1.7 on 2023-03-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_image_height_products_image_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('details', models.CharField(max_length=5000)),
                ('slug', models.SlugField(max_length=255)),
                ('image', models.ImageField(upload_to='static/img/')),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_width',
        ),
    ]
