# Generated by Django 4.1.7 on 2023-03-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_service_delete_products_delete_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='cat_slug',
        ),
    ]
