# Generated by Django 4.1.7 on 2023-03-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_slug_category_cat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
